version: "3.8"
services:
  data-scrapper-service:
    container_name: data-scrapper-service
    image: data-scrapper-service
    build:
      context: ../
      dockerfile: Dockerfile
    command: bash -c "npm install && nodemon"
    volumes:
      - ../../:/app
    ports:
      - 8686:8686
    networks:
      - scrapping-network

networks:
  scrapping-network:
    external:
      name: scrapping-network
