version: '3.9'
services:
    scrapping-service:
        container_name: scrapping-service
        image: scrapping-service
        build:
            context: ../
            dockerfile: Dockerfile
        environment:
            SERVICE_NAME: app
            VIRTUAL_HOST: ${VIRTUAL_HOST_DOMAIN}
        working_dir: /var/www
        entrypoint: /etc/entrypoint.sh
        networks:
            - scrapping_network
        volumes:
            - ../../:/var/www
            - ../nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf
            - ../nginx/conf.d/nginx-local.conf:/etc/nginx/sites-enabled/default
            - ../php/local.ini:/usr/local/etc/php/conf.d/local.ini
            - ../php/memory_limit.ini:/usr/local/etc/php/conf.d/memory_limit.ini
            - ../php/php.ini:/usr/local/etc/php/conf.d/php.override.ini
            - ../php/conf.d/www.local.conf:/usr/local/etc/php-fpm.d/www.conf
            - ../nginx/logs:/var/log/nginx
        ports:
            - 8080:8080
        extra_hosts:
            - ${VIRTUAL_HOST_DOCKER_HOST}:${DOCKER_HOST_ADDR}
            - ${VIRTUAL_HOST_LOCALHOST}:${DOCKER_HOST_ADDR}
networks:
    scrapping_network:
        name: scrapping_network
